"""Capability 17 - the build settings a deployment was ACTUALLY compiled with.

Capability 11 compares normalized runtime bytecode against a local rebuild, and
11-R3 is deliberately strict: if the rebuild does not match byte-for-byte, the
answer is UNKNOWN rather than PATCHED, because a mismatch cannot be told apart
from a compiler-settings difference. That discipline is correct, and it is also
the single biggest reason liveness returns UNKNOWN on real contracts.

The settings were never knowable locally, so they were guessed:

    optimizer runs   hardcoded to 200 (DEFAULT_OPTIMIZE_RUNS)
    optimizer on/off assumed ALWAYS ON whenever runs were passed
    evmVersion       never set at all - solc's default for whatever compiler
                     happened to run

Each of those three can change generated bytecode on its own, and the third is
the worst because it is invisible: a contract built for `istanbul` rebuilt
under a modern compiler's default (`shanghai`/`cancun`) differs in the opcodes
available (PUSH0), so the hashes cannot match no matter how correct everything
else is.

Sourcify publishes exactly these fields for verified contracts, free and
without an API key. Measured against real mainnet contracts:

    88mph NFT   0.5.17+commit.d19bba13  optimizer {runs 200, enabled True}
                evmVersion istanbul
    WETH9       0.4.19+commit.c4cbbb05  optimizer {runs 200, enabled FALSE}
                evmVersion None

WETH is the case that proves the point: Chainwatch would have passed
`--optimize --optimize-runs 200` and produced bytecode the deployment never
had, guaranteeing UNKNOWN.

THIS RAISES RECALL, NEVER PRECISION-RISK. Nothing here relaxes the comparison:
`check_against_artifact` still demands an exact normalized match. Supplying the
real settings only lets a rebuild that SHOULD match actually match. When
Sourcify has no record, every field comes back None and the caller keeps its
previous behaviour exactly - so an unverified contract is no worse off than
before this module existed.
"""

from __future__ import annotations

import os
from typing import Any, Optional

SOURCIFY_BASE = os.environ.get("SOURCIFY_URL", "https://sourcify.dev/server")
DEFAULT_TIMEOUT = 20

# Verified settings are immutable per (chain, address) - a contract's build is
# fixed at deploy time - so this memo can never go stale within a process.
_CACHE: dict[tuple[int, str], dict] = {}


def _empty(reason: str) -> dict:
    """The shape callers get when nothing is known. Every field None so a
    caller can `or` its own default in without special-casing."""
    return {"found": False, "reason": reason, "compiler_version": None,
            "optimize": None, "optimize_runs": None, "evm_version": None,
            "contract_name": None, "match": None}


def settings_for(address: str, chain_id: int = 1,
                 timeout: int = DEFAULT_TIMEOUT) -> dict:
    """Verified build settings for `address`, or an all-None record.

    NEVER raises and never blocks a scan: Sourcify being down, slow, or simply
    not knowing this contract are all ordinary conditions for an analysis
    engine that must work offline. Each returns `found: False` with the reason
    attached, and the caller carries on with its own defaults.
    """
    try:
        key = (int(chain_id), str(address).lower())
    except (TypeError, ValueError):
        return _empty(f"invalid address/chain: {address!r}/{chain_id!r}")
    if key in _CACHE:
        return _CACHE[key]

    try:
        import requests
    except ImportError:  # pragma: no cover - requests ships with web3
        return _empty("requests not installed")

    url = f"{SOURCIFY_BASE}/v2/contract/{key[0]}/{key[1]}?fields=compilation"
    try:
        resp = requests.get(url, timeout=timeout)
    except Exception as exc:  # noqa: BLE001
        # Not cached: a network blip should not poison the whole run.
        return _empty(f"{type(exc).__name__}: {exc}"[:150])

    if resp.status_code == 404:
        out = _empty("not verified on Sourcify")
        _CACHE[key] = out
        return out
    if resp.status_code != 200:
        return _empty(f"sourcify HTTP {resp.status_code}")

    try:
        body = resp.json()
    except Exception as exc:  # noqa: BLE001
        return _empty(f"unparseable response: {type(exc).__name__}")

    comp: dict[str, Any] = body.get("compilation") or {}
    settings: dict[str, Any] = comp.get("compilerSettings") or {}
    optimizer: dict[str, Any] = settings.get("optimizer") or {}

    out = {
        "found": bool(comp),
        "reason": "" if comp else "no compilation record in response",
        # `0.5.17+commit.d19bba13` -> `0.5.17`: solc-select keys on the bare
        # semver, and the commit hash is implied by it.
        "compiler_version": _bare_version(comp.get("compilerVersion")),
        # Explicitly a tri-state. False is MEANINGFUL (WETH), and is not the
        # same as None (unknown) - collapsing them would reintroduce the
        # always-optimize assumption this module exists to remove.
        "optimize": optimizer.get("enabled") if "enabled" in optimizer else None,
        "optimize_runs": optimizer.get("runs"),
        "evm_version": settings.get("evmVersion"),
        "contract_name": comp.get("name"),
        "match": body.get("match"),
    }
    _CACHE[key] = out
    return out


def _bare_version(v: Optional[str]) -> Optional[str]:
    """`0.5.17+commit.d19bba13` -> `0.5.17`. None stays None."""
    if not v:
        return None
    return str(v).split("+", 1)[0].lstrip("v") or None


def describe(rec: dict) -> str:
    """One line for a report or an event, for humans reading a scan log."""
    if not rec.get("found"):
        return f"no verified build settings ({rec.get('reason') or 'unknown'})"
    bits = []
    if rec.get("compiler_version"):
        bits.append(f"solc {rec['compiler_version']}")
    if rec.get("optimize") is not None:
        bits.append(f"optimizer {'on' if rec['optimize'] else 'off'}"
                    + (f" ({rec['optimize_runs']} runs)"
                       if rec.get("optimize_runs") is not None and rec["optimize"]
                       else ""))
    if rec.get("evm_version"):
        bits.append(f"evm {rec['evm_version']}")
    return ", ".join(bits) or "verified, but no settings published"


def clear_cache() -> None:
    _CACHE.clear()
